account/urls.py
from django.urls import path
from account.views import (
    register,
    login,
    dashboard,
    logout,
    acc_home,
    must_authenticate_view
)

urlpatterns =[
    path("", acc_home, name="acc_home"),
    path("register", register, name="register"),
    path("login", login, name="login"),
    path("dashboard", dashboard, name="dashboard"),
    path ("logout", logout, name="logout"),
    path("must_authenticate", must_authenticate_view, name="must_authenticate" ),
]

fediox/urls.py
from django.contrib import admin
from django.urls import path,include
"""
URL configuration for fedro project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/5.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from fediox.settings import MEDIA_ROOT
from django.conf import settings
from django.conf.urls.static import static 
from homic.views import(home_co,home_view)


urlpatterns = [
    

    path("homic/", include(("homic.urls", "homic"), namespace="homic")),
    path("account/", include(("account.urls", "account"), namespace="account")),
    path("personal/", include(("personal.urls", "personal"), namespace="personal")),
    path("video/", include(("video.urls", "video"), namespace="video")),
    path('admin/', admin.site.urls),
    path("", home_co, name="home_co"),
    path("home_view/",home_view, name="home_view"),
]
if settings.DEBUG:
    urlpatterns+= static(settings.MEDIA_URL, document_root=MEDIA_ROOT)

homic/urls.py
from django.urls import path
from homic.views import home_view
    


urlpatterns=[
    path(" ", home_view, name="home_view"),
]

personal/urls.py
from django.urls import path
from personal.views import(
     my_pasio,
     create_question_answer,
     get_question_answer,
     fedo,
     )


urlpatterns =[
    path("", my_pasio, name="my_pasio"),
    path("create_question_answer", create_question_answer, name="create_question_answer"),
    path("get_question_answer", get_question_answer, name="get_question_answer"),
    path("fedo", fedo, name="fedo")
]

video/urls.py
from django.urls import path
from .views import video_home


urlpatterns=[
    path(" ", video_home, name="video_home")
]

homic/models.py
from django.db import models

# Create your models here.

homic/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
# Create your views here.

def home_view(request):
   
    return render(request, 'homic/home_view.html')

def home_co(request):
    return redirect(reverse('home_view'))

homic/templates/homic/home_view.html
{% extends 'base.html' %}
{% load static %}


<!DOCTYPE html>

    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title><h1>giox home page</h1> </title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
        <link rel="stylesheet" type="text/css" href="https://bootswatch.com/4/superhero/bootstrap.min.css">
       <link href="{% static 'homic/css/main.css' %}" rel="stylesheet" type="text/css">
       <link href="{% static 'homic/dashboard.css' %}" rel="styslesheet">
       <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    </head>
    <body>
        <style>
        
            
        </style>
        {% block content %}
<div class="container">
        <div class="g-header">
          <h1>This Is Giox Home Page</h1>
          
        </div>
        
        <div class="my-s">mysite</div>
        
<div class="main-container">
    <div class="main">
          <h1>Welcome to My home Page</h1><hr/>
          <p>This is a Federalism website you are welcom to learn more about it interesting aspects x20
          </p>
          <p>This is a Federalism website you are welcom to learn more about it interesting aspects x20
          </p>
          <p>This is a Federalism website you are welcom to learn more about it interesting aspects x20
          </p>
          <p>This is a Federalism website you are welcom to learn more about it interesting aspects x20
          </p>
          <p>This is a Federalism website you are welcom to learn more about it interesting aspects x20
          </p>
          <p>This is a Federalism website you are welcom to learn more about it interesting aspects x20
          </p>
          <p>This is a Federalism website you are welcom to learn more about it interesting aspects x20
          </p>
          <p>This is a Federalism website you are welcom to learn more about it interesting aspects x20
          </p>
          <p>This is a Federalism website you are welcom to learn more about it interesting aspects x20
          </p>
          <p>This is a Federalism website you are welcom to learn more about it interesting aspects x20
          </p>
          <p>This is a Federalism website you are welcom to learn more about it interesting aspects x20
          </p>
          <p>This is a Federalism website you are welcom to learn more about it interesting aspects x20
          </p>
          <p>This is a Federalism website you are welcom to learn more about it interesting aspects x20
          </p>
          <p>This is a Federalism website you are welcom to learn more about it interesting aspects x20
          </p>
          <p> <h1>dome animation-direction</h1> </p>

    </div>
       <div class=" sidebar1">
        <div class="sidebar1-h"><h1>Sidebar</h1></div>
        <a class="sidebar1-a1"   href="{% url 'homic:home_view'%}">Giox Page</a><br>
        <a class="sidebar1-a2" href="{% url 'personal:my_pasio' %}">Pasio Page</a><br>
        <a class="sidebar1-a3"href="{% url 'account:acc_home' %}">Account</a><br>
        <a class="sidebar1-a7" href="{% url 'video:video_home' %}">Get-me-videos</a><br>
       
    </div>
       <div  class="sidebar2">
       <h1>dome animation-direction</h1>
       <img src="{% static '/homic/images/crowi.jpg/' %}" alt="crowi" />
       <img src="{% static '/homic/images/logo2.jpg/'%} " alt="logo2" />
       <img src="{% static '/homic/images/part-ky.jpg.jpg /' %}" alt="part-ky"  />
       <img src="{% static '/homic/images/pierre.jpg.jpg/' %}" alt="pierre" />
       

    </div>
</div>

     <div class="footer-f">
       <b> <p><em><h1>FEDERALISM IS THE ANSWER TO ALL PAN-AFRICAN COUTRIES!</h1></em></p></b>
    </div>
</div>
        {% endblock content%}
        <script src="https://code.jquery.com/jquery-3.7.1.slim.min.js"
                    integrity="sha256-kmHvs0B+OpCW5GVHUNjv9rOmY0IvSIRcf7zGUDTDQM8="
                    crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"></script>
     
        <script src="" async defer></script>
    </body>
</html>