fediox/urls.py
from django.contrib import admin
from django.urls import path,include
"""
URL configuration for fedro project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/5.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from fediox.settings import MEDIA_ROOT
from django.conf import settings
from django.conf.urls.static import static 
from homic.views import(home_co,home_view)


urlpatterns = [
    

    path("homic/", include(("homic.urls", "homic"), namespace="homic")),
    path("account/", include(("account.urls", "account"), namespace="account")),
    path("personal/", include(("personal.urls", "personal"), namespace="personal")),
    path("video/", include(("video.urls", "video"), namespace="video")),
    path('admin/', admin.site.urls),
    path("", home_co, name="home_co"),
    path("home_view/",home_view, name="home_view"),
]
if settings.DEBUG:
    urlpatterns+= static(settings.MEDIA_URL, document_root=MEDIA_ROOT)

homic/urls.py
from django.urls import path
from homic.views import home_view
    


urlpatterns=[
    path(" ", home_view, name="home_view"),
]

personal/urls.py
from django.urls import path
from personal.views import(
     my_pasio,
     create_question_answer,
     get_question_answer,
     fedo,
     )


urlpatterns =[
    path("", my_pasio, name="my_pasio"),
    path("create_question_answer", create_question_answer, name="create_question_answer"),
    path("get_question_answer", get_question_answer, name="get_question_answer"),
    path("fedo", fedo, name="fedo")
]

personal/models.py
from django.db import models

# Create your models here.
PRIORITY = [
    ("L", "low"),
    ("M", "medium"),
    ("H", "high"),
]


class QuestionAnswer(models.Model):
    title = models.CharField(max_length=60)
    question = models.TextField(max_length=400)
    answer = models.TextField(max_length=300)
    priority = models.CharField(max_length=1, choices=PRIORITY)

    class Meta:
        verbose_name = "The Question, The Answer"
        verbose_name_plural = "User Questions, User Answers"

    def __str__(self):
        return self.title

personal/forms.py
from django.contrib.auth.forms import forms
from django.template.defaultfilters import title

from .models import QuestionAnswer


class QuestionAnswerForm(forms.Form):
    class Meta:
        model = QuestionAnswer
        fields = ["title", "question", "answer", "priority"]
        widgets = {title: forms.TextInput(attrs={"class": "form-control"})}

    def save(self):
        pass


class CreateQuestionAnswerForm(forms.ModelForm):
    class Meta:
        model = QuestionAnswer
        fields = ["title", "question", "answer", "priority"]

personal/views.py
from django.shortcuts import render, redirect
from.models import QuestionAnswer
from .forms import CreateQuestionAnswerForm, QuestionAnswerForm
from django.http import JsonResponse, HttpResponse
# Create your views here.

def my_pasio(request):
    questions = QuestionAnswer.objects.all()
    context={'questions':questions}
    return render(request, 'personal/my_pasio.html', context)

def fedo(request):
    return render(request, 'fedo.html')

"""def question_answer(request):
    if request.method == "POST":
        form = QuestionAnswerForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("authy:question_answer_list")
    else:
        form = QuestionAnswerForm()
        return render(request, "question_answer.html", {"form": form})"""
    

  
def create_question_answer(request):
    form = CreateQuestionAnswerForm()

    if request.method == "POST":
        form = CreateQuestionAnswerForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponse("<em>New Question was created succesfully<em>")
        
    return render(request, "personal/create_question_answer.html", {"form": form})
  

def get_question_answer(request):
    questions = QuestionAnswer.objects.all()
    return JsonResponse({"questions": list(questions.values())})

personal/templates/personal/DEVO.html
<!DOCTYPE html>
<img src=""/>
<html>
    
</html>

personal/templates/personal/create_question_answer.html
{% extends 'base.html' %}
{% load static %}

{% block title %}QuestionAnswerForm{% endblock title%}

{% block content %}
<div class= "content-align-centre"><h2>CreationForm</h2>
<div class= "bl-p-f">
<form   method="POST" id="creation-form"  enctype="multipart/form-data">
  
  {% csrf_token %}
   {{form}}
  <button type="submit">CreationForm</button> 
  </form>
  </div>
</div>

<script src="https://code.jquery.com/jquery-3.7.1.slim.min.js"
			  integrity="sha256-kmHvs0B+OpCW5GVHUNjv9rOmY0IvSIRcf7zGUDTDQM8="
			  crossorigin="anonymous">
  $(document).on('submit', '#creation-form', function(){
       e.preventDefault();
        $.ajax({
          type:'POST',
          url: "{% url 'personal:create_question_answer' %}",
          data:{
          title:$('#title').val(),
          question:$('#question').val(),
          answer:$('#answer').val(),
          priority:$('#priority').val(),
          csrfmiddlewaretoken:$('input[title=csrfmiddleware token]').val(),
        },
        success:function(data){
           alert(data);
        }
      });
  });
  
</script>
  
{% endblock content %}

personal/templates/personal/fedo.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="HTF-8">
        <meta name="viewport" content="width=device-width initial-scale=0.1">
        <title>Loading Animation</title>
        <script  type="text/javscript" src="scipt.js"></script>
        <link ref="stylesheet" href="style.css">
        <style>
            .loading{
                display: flex ;
                align-self: frex-center;
               height: 150px; 
               width: 150px;
               border:6px solid aqua;
               border-radius: 4px;
               box-shadow: 0 0 8px aqua, 0 0 8px aqua inset;
               position: center;
               top:50%;
               left:50px;
               translate: 50%, 50%;
               z-index: 10;
               animation: 2s loading ease-in-out normal;
            }
            @keyframes loading{
                0%{
                    transform: rotateX(0) rotateY(0) rotateZ(0);

                }
                33%{
                    transform:rotateX(180deg) rotateY(0) rotateZ(0);

                }
                67%{
                    transform: rotateX(180deg) rotateY(180deg) rotateZ(180deg);

                }
                100%{
                    transform: rotateX(180deg) rotateY(180deg) rotateZ('angle');
                }

            }
        </style>
    </head>
    <body>
       
        <div class="loading"></div>
       
        
    </body>

</html>

personal/templates/personal/get_question_answer.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<h1>List of Live Data</h1>
<ul id="display-data">

</ul>



<script>
    $(document).ready(function() {
        SetInterval(function(){
          $.ajax({
            type:'GET',
            url:"{% url 'get_question_answer' %}",
            success:function(response){
                 console.log(response);
                 $('#display').empty();
                for(var key in response. Questions){
                var loop ,list ='<h2><li>' + response(Questions[key].name) + '</li></h2>'
                $("#display").append(temp);
            };
            error:function$(response);{
              
              alert("An Error Occurred")
            };
        },
    },1000);

  });




});

</script>

{% endblock %}

personal/templates/personal/my_pasio.html
{% extends 'base.html' %}
{% load static %}
<html>
<haed>

   <meta charset="utf-8">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <title><h1>giox home page    
{% block title %}My Pasionate Page {% endblock title %}  </h1> </title>
   
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <link rel="stylesheet" href="">
   <link rel="stylesheet" type="text/css" href="https://bootswatch.com/4/superhero/bootstrap.min.css">
   <link href="{% static 'homic/css/main.css' %}" rel="stylesheet" type="text/css">
   <link href="{% static 'homic/dashboard.css' %}" rel="styslesheet">
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
 <style>
  
 </style>
</haed>
<body>
{% block content %}

 <div class="mypasio-cont">

    <div class="header-my-p">
      <p>Transformations of Questions</p>
    </div>
  <div class="mypasionate-main">
   
   <div class="graphics-examples"><h1>Title Graphic Examples</h1><hr>
    <img src="{% static '/homic/images/graphicy.png/' %}" alt="graphicy" width="100%">
    <div class="graphic-img">
    
       <div class="img1">
        <img src="{% static '/homic/images/part-ky.jpg.jpg/'%}" alt="part-ky" width="150px"height="250px">
       </div>
       <div class="img2">
        <img src="{% static '/homic/images/crowi.jpg/' %}" alt="crowi" width="150px" height="250px">
       </div>
       <div class="img3">
        <img src="{% static '/homic/images/rose.jpg/' %}" alt="rose" width="145px" height="250px" >
       </div>
       
    </div>
  
  </div>
   <div class="my_pasionate-nav">
    <h1>This Is Pasio-Navbar</h1><hr>
     <ul>
       <a class="my_pasionate-nav-a1" href="{% url 'personal:create_question_answer' %}">CreationForm</a>
       <br>
       <a class="my_pasionate-nav-a2" href="{% url 'personal:get_question_answer' %}">GET-Me-QNA</a><br>
       <a class="my_pasionate-nav-a3" href="{%  url 'personal:fedo' %}">Tempo Demo</a><br>  
     </ul><hr>
     <div class="nav-imo">
     <div class="img4" >

      <img src="{% static '/homic/images/road-to-federalism.jpg/' %}" alt="road-to-federalism"  width="200%" style="border: solid 5px brown;
      border-radius: 10px;">
       </div>
       <div class="img5" >

       <img src="{% static '/homic/images/cosmic.jpg/' %}" alt="cosmic" width="250px" height="220px" style="border: solid 5px blueviolet;
       border-radius: 10px;">
        <p> my slide</p>
       </div>
      </div>

   </div>

   <div class="in-qns">
    <h1>question-List</h1><hr>
     <ol>
         {% for question in questions %}
            {{question.title}}<br>

            {{question.question}}<br>
            {{question.answer}}<br>
            {{question.priority}}<br><hr>
          {% endfor %}  
      </ol> 

    </div>
  </div>
  <div class="mypasio-footer">
    <p>I love federalism quiz questions, they are so educative and soul reviving 
      especially for some tromatized by the brutarity , corruption of highest order,
      neptimizm,arogance of political leader who only care for their families agnaist
       their nations
    </p>
  </div>
</div>

{% endblock content %}
</body>
 <script src="https://code.jquery.com/jquery-3.7.1.slim.min.js"
                    integrity="sha256-kmHvs0B+OpCW5GVHUNjv9rOmY0IvSIRcf7zGUDTDQM8="
                    crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"></script>
     
        <script src="" async defer></script>
</html>